# Generated by Django 5.0.6 on 2024-06-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='data_termino',
        ),
    ]
